version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13.0-browsers
    steps:
      - checkout
      - run:
          name: Installing Linux dependencies'
          command: sudo apt-get install libxtst-dev libpng++-dev sox
      - run:
          name: Installing node packages
          command: npm i
      - run:
          name: Running the node tests
          command: npm test
    no_output_timeout: 45s
